### ISSUE TITLE
Problem with Google Work Profiles (user10 reserved)

### ISSUE THREAD

**Issue by shiftykey** [thulasi-ram/simple_android_debloater#11]
While trying to list packages it errors out:

"ADB Error \nException occurred while executing 'list':\njava.lang.SecurityException: Shell does not have permission to access user 10\n com.android.server.am.ActivityManagerService.handleIncomingUser:14983 android.app.ActivityManager.handleIncomingUser:4805 com.android.server.pm.PackageManagerShellCommand.translateUserId:3517 \n\tat com.android.server.am.UserController.handleIncomingUser(UserController.java:2680)\n\tat com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:14983)\n\tat android.app.ActivityManager.handleIncomingUser(ActivityManager.java:4805)\n\tat com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3517)\n\tat com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:969)\n\tat com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:865)\n\tat com.android.server.pm.PackageManagerShellCommand.runList(PackageManagerShellCommand.java:724)\n\tat com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:226)\n\tat com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)\n\tat android.os.ShellCommand.exec(ShellCommand.java:38)\n\tat com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7071)\n\tat android.os.Binder.shellCommand(Binder.java:1085)\n\tat android.os.Binder.onTransact(Binder.java:903)\n\tat android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4962)\n\tat com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7055)\n\tat android.os.Binder.execTransactInternal(Binder.java:1321)\n\tat android.os.Binder.execTransact(Binder.java:1280)"

Here is some information on work profiles from google: https://developer.android.com/work/managed-profiles

**Comment by thulasi-ram** [comment]
Thanks for the report. This is handled in UAD but not in this. Will try and pick it up.

It requires enumerating all users and then catching the error and not listing them / list them as disabled.

**Comment by thulasi-ram** [comment]
@shiftykey Can you confirm if the list is failing for all users or only when selected via drop down?

It seems that UAD doesn't execute actions on ProtectedUsers and they display the same in the settings

https://github.com/0x192/universal-android-debloater/blob/11f27c671cba278d71296cdef4c5a5dba06add5e/src/core/sync.rs#L286
